from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from datetime import date
from typing import List
from pydantic import BaseModel
import os
import subprocess

# Internal imports
from models import SessionLocal, VirtualFridge

app = FastAPI(
    title="ZeroCart API", 
    description="Edge-Compute Grocery Backend", 
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# -----------------
# PYDANTIC SCHEMAS (For input/output validation)
# -----------------
class FridgeItemCreate(BaseModel):
    user_id: int
    item_name: str
    category: str
    quantity: float
    unit: str
    expiration_date: date

class FridgeItemResponse(FridgeItemCreate):
    id: int

    class Config:
        from_attributes = True

# -----------------
# API ENDPOINTS
# -----------------

@app.get("/")
def read_root():
    return {"status": "success", "message": "ZeroCart Brain is online"}

@app.post("/api/v1/fridge/add", response_model=FridgeItemResponse)
def add_to_fridge(item: FridgeItemCreate, db: Session = Depends(get_db)):
    """Add a new item to the Virtual Fridge."""
    # Convert incoming Pydantic validation schema to SQLAlchemy database model directly
    db_item = VirtualFridge(**item.model_dump())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return db_item

@app.get("/api/v1/fridge/{user_id}", response_model=List[FridgeItemResponse])
def get_fridge(user_id: int, db: Session = Depends(get_db)):
    """Retrieve all current inventory in the fridge for a specific user."""
    items = db.query(VirtualFridge).filter(VirtualFridge.user_id == user_id).all()
    return items

@app.delete("/api/v1/fridge/remove/{item_id}")
def remove_from_fridge(item_id: int, db: Session = Depends(get_db)):
    """Manually delete an item from the fridge (simulates consuming it)."""
    db_item = db.query(VirtualFridge).filter(VirtualFridge.id == item_id).first()
    if not db_item:
        raise HTTPException(status_code=404, detail="Item not found in your fridge")
    
    db.delete(db_item)
    db.commit()
    return {"message": f"Successfully consumed item {item_id}"}


# -----------------
# PHASE 1B: LIVE EDGE SCRAPING
# -----------------

from logic.llm_scraper import get_live_deals
import models

@app.post("/api/v1/sync_live_prices")
def sync_live_prices(db: Session = Depends(get_db)):
    """
    Triggers an Agentic Web Scrape via Gemini Search to autonomously
    index the current grocery landscape bypassing all Cloudflare limitations.
    """
    output = get_live_deals()
    
    if output.get("status") == "success":
        deals = output.get("deals", [])
        
        # Wipe old "Tesco Live" mock data safely
        db.query(models.LocalDeal).filter(models.LocalDeal.store_name == "Tesco Live").delete()
        
        # Inject new live deals precisely generated by the LLM
        for deal_data in deals:
            try:
                new_deal = models.LocalDeal(
                    store_name=deal_data.get("store_name", "Tesco Live"),
                    sku=deal_data.get("sku"),
                    item_name=deal_data.get("item_name"),
                    price=deal_data.get("price"),
                    price_per_unit=deal_data.get("price_per_unit"),
                    item_url=deal_data.get("url", ""),
                    protein_grams=deal_data.get("protein_grams"),
                    calories=deal_data.get("calories")
                )
                db.add(new_deal)
            except Exception as e:
                print(f"Error saving AI Scraping deal: {e}")
        
        db.commit()
        return {"status": "success", "message": f"Synchronized {len(deals)} items autonomously."}
    else:
        # If Agent Search fails totally
        raise HTTPException(status_code=500, detail="Failed to sync deals via LLM Scraper")

class UserProfileUpdate(BaseModel):
    weekly_budget: float | None
    calorie_limit: int | None
    family_size: int
    meal_types_wanted: str
    preferred_store: str

@app.get("/api/v1/user/{user_id}")
def get_user_profile(user_id: int, db: Session = Depends(get_db)):
    import models
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return user

@app.put("/api/v1/user/{user_id}")
def update_user_profile(user_id: int, profile: UserProfileUpdate, db: Session = Depends(get_db)):
    import models
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    
    user.weekly_budget = profile.weekly_budget
    user.calorie_limit = profile.calorie_limit
    user.family_size = profile.family_size
    user.meal_types_wanted = profile.meal_types_wanted
    user.preferred_store = profile.preferred_store
    
    db.commit()
    return {"status": "success", "user": user}

# -----------------
# PHASE 2: MATH ENGINE ENDPOINTS
# -----------------

@app.post("/api/v1/optimize_basket")
def trigger_math_engine(user_id: int, store_name: str = "Tesco Blackburn", db: Session = Depends(get_db)):
    """Generate perfect basket using Google OR-Tools Constraint Solver."""
    from logic.constraint_solver import optimize_basket
    from models import User
    
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
        
    # We pass the full user explicitly to the solver
    result = optimize_basket(db=db, user=user, store_name=store_name)
    return result


# -----------------
# PHASE 3: GEMINI RECIPE ORCHESTRATOR
# -----------------

@app.post("/api/v1/generate_plan")
def generate_weekly_plan(user_id: int, store_name: str = "Tesco Blackburn", db: Session = Depends(get_db)):
    """Generates a 7-day meal plan based on the Math Engine output."""
    from logic.constraint_solver import optimize_basket
    from logic.llm_chef import generate_recipe_plan
    from models import User
    
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
        
    # 1. Run the left-brain Math Engine
    # We pass the full user object so the math engine can adapt to mouths to feed, calories, etc.
    basket_result = optimize_basket(db=db, user=user, store_name=store_name)
    
    if basket_result.get("status") != "success":
        raise HTTPException(status_code=400, detail="Math Engine failed to build a valid basket.")
        
    # 2. Extract the raw ingredient payload
    basket_items = basket_result.get("basket", [])
    
    # 3. Pass it directly to the right-brain Gemini LLM
    llm_result = generate_recipe_plan(basket=basket_items, user=user)
    
    if llm_result.get("status") == "error":
        raise HTTPException(status_code=500, detail=f"LLM Error: {llm_result.get('message')}")
        
    # Return the combined masterpiece
    return {
        "basket_summary": basket_result.get("summary"),
        "basket_items": basket_items,
        "meal_plan": llm_result.get("plan")
    }

@app.post("/api/v1/generate_single_meal")
def generate_single_meal(day: str, user_id: int, store_name: str = "Tesco Blackburn", db: Session = Depends(get_db)):
    """Generates ONE substitute meal for a specific day."""
    from logic.constraint_solver import optimize_basket
    from logic.llm_chef import generate_single_recipe
    from models import User
    
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
        
    basket_result = optimize_basket(db=db, user_id=user_id, budget=user.weekly_budget, min_protein=400.0, store_name=store_name)
    if basket_result.get("status") != "success":
        raise HTTPException(status_code=400, detail="Math Engine failed to build a valid basket.")
        
    basket_items = basket_result.get("basket", [])
    llm_result = generate_single_recipe(day=day, basket=basket_items)
    
    if llm_result.get("status") == "error":
        raise HTTPException(status_code=500, detail=f"LLM Error: {llm_result.get('message')}")
        
    return llm_result

@app.get("/api/v1/generate_meal_image")
def get_meal_image(recipe_name: str):
    from logic.llm_chef import generate_dish_image
    result = generate_dish_image(recipe_name)
    if result.get("status") == "error":
        raise HTTPException(status_code=500, detail=result.get("message"))
    return {"image_base64": result.get("image_base64")}

# -----------------
# PHASE 5: PWA INTERFACE
# -----------------

@app.post("/api/v1/cart/approve")
def approve_cart(user_id: int):
    """
    Called by the PWA. Approves the basket and fires the Playwright browser automation
    to autonomously navigate to Tesco/ASDA and purchase the items.
    """
    print(f"User {user_id} approved the cart! Firing Edge Agent subprocess...")
    
    try:
        # Fire the Edge Agent asynchronously
        subprocess.Popen(
            ["node", "../../edge-client/cart_injector.js"],
            cwd=os.path.abspath(os.path.dirname(__file__))
        )
        return {"status": "success", "message": "Edge Agent launched. Check your Monzo app for payment approval."}
    except Exception as e:
        print(f"Failed to launch Edge Agent: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to launch Playwright agent: {str(e)}")
